### ISSUE TITLE
TTD Class feedback

### ISSUE THREAD

**Issue by johnfitzpatrick** [chef-training/test_driven_cookbook_development#1]
(ToDo for JohnF - Tidy this up and split into individual issues)

CH03
#21 – they need to change 7.1 to 6.7, not just remove Ubuntu
#23 - Kitchen create takes ~2 mins.  Can we run this before we create the AMI so the container is preloaded.

CH04
#11 – should show the ‘file’ resource is still in the recipe
#21 – file resource should show
#25 – files before serverspec, as the file resource is still in the default recipe, so chef-client run bombs

CH05
Last section was about Serverspec & kitchen.  This section is about ChefSpec, but chefspec isn’t mentioned until slide 13, nor is the diff between it & serverspec, or why kitchen isn’t required.  Maybe this should be first, as they can run this against code before using sevrspec w/ actual infrastructure.  Fundamentals/Essentials alumni may not be aware of chefspec
#5 – I’m seeing the three '_spec.rb' files, one for each the recipe in from previous section

CH06
This section starts by introducing chef spec – but we’ve already used it in previous section
#6 – this is a repeat of previous section
#18 – Is this after "it 'converges successfully' do” statement? I guess it is, but should stipulate that to head off errors

CH07
I think this section could teach a lot more about PRY – maybe that's in a later lesson
#23 – I didn’t `get ‘=> nil’` - I got this:-

```
[2] pry(#<Chef::Recipe>)> node['httpd']
=> {"package_name"=>"httpd”}
```
#24 – OK, seems the output from slide 23 & 24 is reversed.

CH08
I think the cookbook should be called apache, as later on we say “default['httpd']['package_name'] = 'apache2’ “ - the ‘httpd’ here doesn’t sit well.
#29 – My centos is ‘Created’, so output is different. That's no issue, but we never explicitly did ‘kitchen setup’ in the labs – went straight to ‘verify'
#31 – when running ‘kitchen test’ for the two platforms, might be nice to show them being tested in parallel with  `kitchen test –c 2`.  However, seems slow on this t1.micro.

CH09
#14 – are we leaving the first describe statement in? If so need to change the “should match(/Apache 2 Test Page/) “ (or highlight in green to show they need to edit it).  This slide doesn’t have a title – is it finished?  Maybe not as we don’t do ‘kitchen verify to run the tests.
#16 We should swap out LWRPs for custom resources – not sure if you can ‘chef generate’ that though.  This section doesn’t meet the objectives in slide 2 – we should go that extra step and create the custom ‘vhosts’ resource the ‘vhosts.rb’ file is there but its empty.  Something like this, and pulling out the attributes (although this doesn’t actually create a new vhost!)

**$ cat recipes/default.rb**

```
#
# Cookbook Name:: httpd
# Recipe:: default
#
# Copyright (c) 2016 The Authors, All Rights Reserved.

include_recipe 'httpd::web’
```

**$ cat recipes/web.rb**

```
#
# Cookbook Name:: httpd
# Recipe:: web
#
# Copyright (c) 2016 The Authors, All Rights Reserved.

httpd_vhost “newvhost”
```

**$ cat resources/vhost.rb**

```
default_action :create
action :create do
package node['httpd']['package_name']

service node['httpd']['service_name'] do
  action [:enable, :start]
end

file '/var/www/html/index.html' do
  content '<h1>Welcome Home!</h1>'
end
end
```

**Comment by burtlo** [comment]
@johnfitzpatrick from module 5 onward you are seeing slide decks that are all command complete but without conceptual slides. So I never explain any detail about ChefSpec, etc. Here is the current progress of the [TDD Cookbook Development course](https://trello.com/c/z4bRjCof/60-course-test-driven-cookbook-development). This week I am finishing quite a bit of the content.

You also have discovered that when I recently taught this course I started to add the file resource to write out the default HTML file. The slides in the later sections have not been updated.

The LWRP / Custom Resource section is not currently taught in this course. I think that it may be a future second day.

**Comment by burtlo** [comment]
I added an issue to pre-fetch for the new workstation release: https://github.com/chef-training/chefdk-image/issues/10

**Comment by burtlo** [comment]
#31 – when running ‘kitchen test’ for the two platforms, might be nice to show them being tested in parallel with kitchen test –c 2. However, seems slow on this t1.micro.

That is an interesting idea and a bonus thing that I would to use later.

**Comment by burtlo** [comment]
Alright so the content is finished and I am sure there that the output is completely wrong on a few slides. I will get them in the next release after I run this class live one more time.

The custom resources section has now been moved to a branch so as not to make it look like it is done.

I left the name of the cookbook 'httpd' because I planned on copying the building of the community 'httpd' cookbook with this content.

**Comment by burtlo** [comment]
I would love for you to take another review of the content again now that it is complete.

**Comment by johnfitzpatrick** [comment]
I'll run through it again early this week.
